/* THE SOURCE CODE AND ITS
 * RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA CORPORATION MAKES NO OTHER
 * WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR, STATUTORY AND DISCLAIMS ANY
 * AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, NON
 * INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. THE SOURCE CODE AND
 * DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA CORPORATION RESERVES THE RIGHT TO
 * INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER REVISIONS OF IT, AND TO
 * MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR THE PRODUCTS OR
 * TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME. TOSHIBA CORPORATION SHALL NOT BE
 * LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGE OR LIABILITY ARISING
 * FROM YOUR USE OF THE SOURCE CODE OR ANY DOCUMENTATION, INCLUDING BUT NOT
 * LIMITED TO, LOST REVENUES, DATA OR PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL
 * OR CONSEQUENTIAL NATURE, PUNITIVE DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS
 * ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF
 * ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM
 * FOR SUCH DAMAGE IS BASED UPON WARRANTY, CONTRACT, TORT, NEGLIGENCE OR
 * OTHERWISE. (C)Copyright TOSHIBA CORPORATION 2011 All rights reserved
 */

#undef _MOTOR_DEFINE_H_

/* Motor Parameter */
#undef  MOTOR_POLE_PAIRS
#undef  MOTOR_DIRECTION
#undef  MOTOR_ENCODER_TYPE
#undef  MOTOR_ENCODER_RESOLUTION
#undef  MOTOR_RESOLUTION_MULT
#undef  MOTOR_ANGULAR_ACC_MAX
#undef  MOTOR_TORQUE_MAX
#undef  MOTOR_RESISTANCE
#undef  MOTOR_INDUCTANCE
#undef  MOTOR_HZ_LIMIT
#undef  MOTOR_HZ_CHANGE
#undef  MOTOR_INIT_DELAY
#undef  MOTOR_IQ_START
#undef  MOTOR_ID_START
#undef  MOTOR_IQ_LIM
#undef  MOTOR_ID_LIM
#undef  MOTORID

/* Control Loop Parameter */
#undef  CONTROL_ID_KI
#undef  CONTROL_ID_KP
#undef  CONTROL_IQ_KI
#undef  CONTROL_IQ_KP
#undef  CONTROL_POSITION_KI
#undef  CONTROL_POSITION_KP
#undef  CONTROL_SPEED_KI
#undef  CONTROL_SPEED_KP

/* System Parameter */
#undef  SYSTEM_DEAD_TIME
#undef  SYSTEM_PWM_FREQUENCY
#undef  SYSTEM_SHUTDOWN_MODE
#undef  SYSTEM_RESTART_MODE
#undef  SYSTEM_STALL_VALUE
#undef  SYSTEM_OVERTEMP_VALUE
#undef  SYSTEM_SPEED_CONTROL_MODE
