/* THE SOURCE CODE AND ITS
 * RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA CORPORATION MAKES NO OTHER
 * WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR, STATUTORY AND DISCLAIMS ANY
 * AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, NON
 * INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. THE SOURCE CODE AND
 * DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA CORPORATION RESERVES THE RIGHT TO
 * INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER REVISIONS OF IT, AND TO
 * MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR THE PRODUCTS OR
 * TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME. TOSHIBA CORPORATION SHALL NOT BE
 * LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGE OR LIABILITY ARISING
 * FROM YOUR USE OF THE SOURCE CODE OR ANY DOCUMENTATION, INCLUDING BUT NOT
 * LIMITED TO, LOST REVENUES, DATA OR PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL
 * OR CONSEQUENTIAL NATURE, PUNITIVE DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS
 * ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF
 * ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM
 * FOR SUCH DAMAGE IS BASED UPON WARRANTY, CONTRACT, TORT, NEGLIGENCE OR
 * OTHERWISE. (C)Copyright TOSHIBA CORPORATION 2011 All rights reserved
 */

#ifndef TMPM37SIGMA_SPI_DEVICE_H
#define TMPM37SIGMA_SPI_DEVICE_H

#include "TMPM372.h"

typedef enum
{
  SPI_DEVICE_CAN,
  SPI_DEVICE_EEPROM,
  SPI_DEVICE_AMP_V_I_DCBUS,
  SPI_DEVICE_AMP_V_I_PH_U,
  SPI_DEVICE_AMP_V_I_PH_V,
  SPI_DEVICE_AMP_V_I_PH_W,
} SPI_DeviceSelect;

uint8_t SPI_GetLEDStatus  (void);
void    SPI_SetLEDStatus  (uint8_t status);
void    SPI_SelectDevice  (SPI_DeviceSelect device);
void    SPI_DeselectDevice(void);
void    SPI_TransmitByte  (TSB_SC_TypeDef* SPIx, uint8_t byte);
uint8_t SPI_ReceiveByte   (TSB_SC_TypeDef* SPIx);
void    SPI_TransmitBytes (TSB_SC_TypeDef* SPIx, uint8_t* bytes, uint8_t number);
void    SPI_ReceiveBytes  (TSB_SC_TypeDef* SPIx, uint8_t* bytes, uint8_t number);
void    SPI_DeviceInit    (uint32_t speed);
#endif
