/* THE SOURCE CODE AND ITS
 * RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA CORPORATION MAKES NO OTHER
 * WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR, STATUTORY AND DISCLAIMS ANY
 * AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, NON
 * INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. THE SOURCE CODE AND
 * DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA CORPORATION RESERVES THE RIGHT TO
 * INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER REVISIONS OF IT, AND TO
 * MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR THE PRODUCTS OR
 * TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME. TOSHIBA CORPORATION SHALL NOT BE
 * LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGE OR LIABILITY ARISING
 * FROM YOUR USE OF THE SOURCE CODE OR ANY DOCUMENTATION, INCLUDING BUT NOT
 * LIMITED TO, LOST REVENUES, DATA OR PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL
 * OR CONSEQUENTIAL NATURE, PUNITIVE DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS
 * ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF
 * ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM
 * FOR SUCH DAMAGE IS BASED UPON WARRANTY, CONTRACT, TORT, NEGLIGENCE OR
 * OTHERWISE. (C)Copyright TOSHIBA CORPORATION 2011 All rights reserved
 */

#include "config.h"
#ifdef USE_I2C_MASTER
#include "FreeRTOS.h"
#include "task.h"
#include "debug.h"
#include "m37sigma_i2c_eeprom.h"
#include "i2c_master_bitbanging.h"

uint8_t I2C_EEPROM_ReadByte(uint8_t device_id, uint8_t offset)
{
    I2C_WriteByte(1,0,device_id<<1);
    I2C_WriteByte(0,0,offset);
    I2C_WriteByte(1,0,(device_id<<1)|DEVICE_READ);
    return I2C_ReadByte(1,1);
}

void I2C_EEPROM_WriteByte(uint8_t device_id, uint8_t offset, uint8_t byte)
{
    I2C_WriteByte(1,0,device_id<<1);
    I2C_WriteByte(0,0,offset);
    I2C_WriteByte(0,1,byte);
    vTaskDelay( 2 / portTICK_RATE_MS );
}

void I2C_EEProm_Test(void)
{
  uint8_t i;
  
  for (i=0;i<8;i++)
    I2C_EEPROM_WriteByte(DEVICE_ID, i,i);

  for (i=0;i<8;i++)
    dprintf("EEProm Offset %d:%x\n",i,I2C_EEPROM_ReadByte(DEVICE_ID, i));
  
  dprintf("Finished\n");
}
#endif