/* THE SOURCE CODE AND ITS
 * RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA CORPORATION MAKES NO OTHER
 * WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR, STATUTORY AND DISCLAIMS ANY
 * AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, NON
 * INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. THE SOURCE CODE AND
 * DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA CORPORATION RESERVES THE RIGHT TO
 * INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER REVISIONS OF IT, AND TO
 * MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR THE PRODUCTS OR
 * TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME. TOSHIBA CORPORATION SHALL NOT BE
 * LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGE OR LIABILITY ARISING
 * FROM YOUR USE OF THE SOURCE CODE OR ANY DOCUMENTATION, INCLUDING BUT NOT
 * LIMITED TO, LOST REVENUES, DATA OR PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL
 * OR CONSEQUENTIAL NATURE, PUNITIVE DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS
 * ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF
 * ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM
 * FOR SUCH DAMAGE IS BASED UPON WARRANTY, CONTRACT, TORT, NEGLIGENCE OR
 * OTHERWISE. (C)Copyright TOSHIBA CORPORATION 2011 All rights reserved
 */

#ifndef EXTERNAL_SPEED_CONTROL
#define EXTERNAL_SPEED_CONTROL

#define ESC_CHANNEL                     1

#define SPEED_CONTROL_ADC_PORT          GPIO_PJ
#define SPEED_CONTROL_ADC_PIN           GPIO_BIT_1
#define SPEED_CONTROL_ADC_CHANNEL       TSB_ADB
#define SPEED_CONTROL_ADC_REG           ADC_REG4
#define SPEED_CONTROL_ADC_HANDLER       INTADBTMR_IRQHandler
#define SPEED_CONTROL_ADC_IRQ           INTADBTMR_IRQn

#define SPEED_CONTROL_PWM_PORT          GPIO_PA
#define SPEED_CONTROL_PWM_PIN           GPIO_BIT_7
#define SPEED_CONTROL_PWM_TMRB          TSB_TB4

#define SPEED_CONTROL_PWM_HANDLER       INTCAP41_IRQHandler
#define SPEED_CONTROL_PWM_IRQ           INTCAP41_IRQn
#define SPEED_CONTROL_PWM_HANDLER2      INTTB41_IRQHandler
#define SPEED_CONTROL_PWM_IRQ2          INTTB41_IRQn

#define SPEED_CONTROL_CWCCW_PORT        GPIO_PA
#define SPEED_CONTROL_CWCCW_PIN         GPIO_BIT_2

#define SPEED_CONTROL_FAULT_PORT        GPIO_PA
#define SPEED_CONTROL_FAULT_PIN         GPIO_BIT_1

#define SPEED_CONTROL_FG_PORT           GPIO_PA
#define SPEED_CONTROL_FG_PIN            GPIO_BIT_3

void EXTERNAL_SPEED_CONTROL_Init( void );

#endif /* EXTERNAL_SPEED_CONTROL */
