/* THE SOURCE CODE AND ITS
 * RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA CORPORATION MAKES NO OTHER
 * WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR, STATUTORY AND DISCLAIMS ANY
 * AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, NON
 * INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. THE SOURCE CODE AND
 * DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA CORPORATION RESERVES THE RIGHT TO
 * INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER REVISIONS OF IT, AND TO
 * MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR THE PRODUCTS OR
 * TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME. TOSHIBA CORPORATION SHALL NOT BE
 * LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGE OR LIABILITY ARISING
 * FROM YOUR USE OF THE SOURCE CODE OR ANY DOCUMENTATION, INCLUDING BUT NOT
 * LIMITED TO, LOST REVENUES, DATA OR PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL
 * OR CONSEQUENTIAL NATURE, PUNITIVE DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS
 * ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF
 * ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM
 * FOR SUCH DAMAGE IS BASED UPON WARRANTY, CONTRACT, TORT, NEGLIGENCE OR
 * OTHERWISE. (C)Copyright TOSHIBA CORPORATION 2011 All rights reserved
 */
#ifndef _PGA_H_
#define _PGA_H_

#include "m372stk_spi_device.h"

typedef enum
{
  GAIN_1,   /* Gain of +1 */
  GAIN_2,   /* Gain of +2 */
  GAIN_4,   /* Gain of +4 */
  GAIN_5,   /* Gain of +5 */
  GAIN_8,   /* Gain of +8 */
  GAIN_10,  /* Gain of +10 */
  GAIN_16,  /* Gain of +16 */
  GAIN_32,  /* Gain of +32 */
} PGA_GAIN;

typedef enum
{
  GAIN_REGISTER    = 0x40,
  CHANNEL_REGISTER = 0x41,
} PGA_INSTRUCTION;

typedef enum
{ CHANNEL0,
  CHANNEL1,
} PGA_CHANNEL;

typedef struct
{
  SPI_DeviceSelect  device;
  PGA_GAIN          gain;
} PGA_Settings;

void PGA_SetChannel (SPI_DeviceSelect device, PGA_CHANNEL channel);
void PGA_Init       (PGA_Settings* settings, uint8_t nr_settings);
#endif /* _PGA_H_ */
