#undef BOARD_DEAD_TIME
#undef BOARD_SENSITIVITY_VOLTAGE_MEASURE
#undef BOARD_SENSITIVITY_CURRENT_MEASURE
#undef BOARD_MEASUREMENT_TYPE
#undef BOARD_SENSOR_DIRECTION
#undef BOARD_POLL
#undef BOARD_POLH
