/* THE SOURCE CODE AND ITS
 * RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA CORPORATION MAKES NO OTHER
 * WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR, STATUTORY AND DISCLAIMS ANY
 * AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, NON
 * INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. THE SOURCE CODE AND
 * DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA CORPORATION RESERVES THE RIGHT TO
 * INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER REVISIONS OF IT, AND TO
 * MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR THE PRODUCTS OR
 * TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME. TOSHIBA CORPORATION SHALL NOT BE
 * LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGE OR LIABILITY ARISING
 * FROM YOUR USE OF THE SOURCE CODE OR ANY DOCUMENTATION, INCLUDING BUT NOT
 * LIMITED TO, LOST REVENUES, DATA OR PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL
 * OR CONSEQUENTIAL NATURE, PUNITIVE DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS
 * ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF
 * ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM
 * FOR SUCH DAMAGE IS BASED UPON WARRANTY, CONTRACT, TORT, NEGLIGENCE OR
 * OTHERWISE. (C)Copyright TOSHIBA CORPORATION 2011 All rights reserved
 */

#include "config.h"
#if (defined BOARD_M374STK)

#include BOARD_BOARD_HEADER_FILE
#include BOARD_PGA_HEADER_FILE
#include "motorctrl.h"

void BOARD_SetupGain(void)
{
  PGA_Settings  pga[] =
  {
    { SPI_DEVICE_AMP_V_I_DCBUS, GAIN_1},
    { SPI_DEVICE_AMP_V_I_PH_U , GAIN_1},
    { SPI_DEVICE_AMP_V_I_PH_V , GAIN_1},
    { SPI_DEVICE_AMP_V_I_PH_W , GAIN_1},
  };
	
	
	pga[0].gain = (PGA_GAIN)ChannelValues[1].gain_vdc;
	pga[1].gain = (PGA_GAIN)ChannelValues[1].gain_current;
	pga[2].gain = (PGA_GAIN)ChannelValues[1].gain_current;
	pga[3].gain = (PGA_GAIN)ChannelValues[1].gain_current;
	
  PGA_Init(pga, sizeof(pga) / sizeof(PGA_Settings));
}

#endif /* BOARD_M374STK */
