/* THE SOURCE CODE AND ITS
 * RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA CORPORATION MAKES NO OTHER
 * WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR, STATUTORY AND DISCLAIMS ANY
 * AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, NON
 * INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. THE SOURCE CODE AND
 * DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA CORPORATION RESERVES THE RIGHT TO
 * INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER REVISIONS OF IT, AND TO
 * MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR THE PRODUCTS OR
 * TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME. TOSHIBA CORPORATION SHALL NOT BE
 * LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGE OR LIABILITY ARISING
 * FROM YOUR USE OF THE SOURCE CODE OR ANY DOCUMENTATION, INCLUDING BUT NOT
 * LIMITED TO, LOST REVENUES, DATA OR PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL
 * OR CONSEQUENTIAL NATURE, PUNITIVE DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS
 * ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF
 * ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM
 * FOR SUCH DAMAGE IS BASED UPON WARRANTY, CONTRACT, TORT, NEGLIGENCE OR
 * OTHERWISE. (C)Copyright TOSHIBA CORPORATION 2011 All rights reserved
 */

#include "config.h"
#include "amp_cmp.h"
#include "tx03_common.h"

#include "TMPM370.h"

/*! \brief  Setup the Amplifier & Comperator
  *
  * @param  cmp_channel:  channel to configure
  * @param  gain:         gain for the amplifier
  * @retval None  
*/
void AMPCMP_setup(M370_AMPCMP_CHANNEL cmp_channel, M370_GAIN gain)
{
  switch (cmp_channel)
  {
  case CHANNEL_A:
    TSB_CMP->CTLA = CMP_ENABLE | CMP_OPAMP_OUT;
    TSB_AMP->CTLA = gain << 1 | AMP_ENABLE;
    break;
  case CHANNEL_B:
    TSB_CMP->CTLB = CMP_ENABLE | CMP_OPAMP_OUT;
    TSB_AMP->CTLB = gain << 1 | AMP_ENABLE;
    break;
  case CHANNEL_C:
    TSB_CMP->CTLC = CMP_ENABLE | CMP_OPAMP_OUT;
    TSB_AMP->CTLC = gain << 1 | AMP_ENABLE;
    break;
  case CHANNEL_D:
    TSB_CMP->CTLD = CMP_ENABLE | CMP_OPAMP_OUT;
    TSB_AMP->CTLD = gain << 1 | AMP_ENABLE;
    break;
  default:
    assert_param(0);
    break;
  }
}   
